### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.OUTPUT_MID_LAYER'

### ISSUE THREAD

**Issue by jokc28** [dragonlzm/ISAL#5]
Hi, I am currently trying to reproduce your work based on the code uploaded on github. 
I wanted to do a quick training run on classification task based on the below command line. 
bash run_isal.sh /workdir /datadir \
    pycls/configs/archive/cifar/resnet/R-18_nds_1gpu.yaml \
    --mining-method=influence --random-seed=0
However, I kept getting the error mentioned above, saying there is non-existent config key. 
I tried googling but was out of luck. Hope you can advise me on how to appropriately reproduce your work, especially on classification task. 
Thank you for your inspiring work.

**Comment by dragonlzm** [comment]
could you please attach a screenshot of the error?

**Comment by jokc28** [comment]
![error](https://user-images.githubusercontent.com/57519005/154624757-00889305-04a5-45dc-b132-6d1798e14cef.png)

Thank you for your help in advance. 
It would be grateful if you can give me some advice on how to fix the issue shown on the screenshot.

**Comment by dragonlzm** [comment]
You can see in the file "https://github.com/dragonlzm/ISAL/blob/main/classification/src/train.py", it imports the pycls.core.config as config. The code logic here should import the content from the file here: "https://github.com/dragonlzm/ISAL/blob/main/classification/pycls/pycls/core/config.py". but from the error info you provided, it seems the code is importing the module from your installed pycls library.
Hoping this can help you.
